name: Build apk

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        cache: gradle
    - uses: gradle/actions/setup-gradle@v4
      with:
        gradle-version: '8.14'
    - run: gradle build
    - uses: actions/upload-artifact@v4
      with:
        name: debug-apks 
        path: app/build/outputs/apk/debug/**
