name: Build apk

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: graalvm/setup-graalvm@v1
      with:
        java-version: '21'
        distribution: 'graalvm'
        cache: gradle
    - run: sh ./gradlew build
    - uses: actions/upload-artifact@v3
      with:
        name: debug-apks 
        path: app/build/outputs/apk/debug/**
